name: shift-python-utilities
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - intake=0.6.8
  - numpy=1.23.5
  - fsspec=2022.11.0
  - intake-xarray=0.6.1
  - xarray=2023.4.2
  - rioxarray=0.14.1
  - geopandas=0.13.0
  - affine=2.4.0
  - dask=2023.5.0
  - rasterio=1.3.7
  - gdal=3.7.0